#

diff --git a/.github/workflows/build-package.yml b/.github/workflows/build-package.yml
--- a/.github/workflows/build-package.yml
+++ b/.github/workflows/build-package.yml
@@ -56,31 +56,37 @@ jobs:
         shell: su buildbot -c "bash {0}"
         working-directory: /builder
         run: |
+          OFFICIAL_PACKAGES=$(echo;cd feeds/plugin/;find package -maxdepth 1 -not -path package -exec sh -c 'd={};[ ! -f "$d/Makefile" ] && basename $d' \;| xargs)
           PACKAGES=
-
-          extra_feeds="helloworld openclash plugin"
+          PACKAGES+=$OFFICIAL_PACKAGES
+          CUSTOM_FEEDS="openclash plugin"
           
-          for f in $extra_feeds;do
-            PACKAGES+=$(echo;./scripts/feeds list -r $f | awk '{print $1}' | xargs)
-          done
-
-          plugin_package_dirs="package luci"
-          for f in $plugin_package_dirs;do
-            PACKAGES+=$(echo;cd feeds/plugin/;find $f -maxdepth 1 -not -path $f -exec sh -c 'd={};[ ! -f "$d/Makefile" ] && basename $d' \;| xargs)
+          for t in $CUSTOM_FEEDS;do
+            PACKAGES+=$(echo;./scripts/feeds list -r $t | sed '/i18n/d' | awk '{print $1}' | xargs)
           done
           
           PACKAGES="${PACKAGES:-luci-app-attendedsysupgrade}"
 
-          echo "Custom packages: $PACKAGES"
-          
-          for PKG in $PACKAGES;do
-            make BUILD_LOG=1 CONFIG_AUTOREMOVE=y -j "$(nproc)" "package/$PKG/compile"
+          echo "Build packages: $PACKAGES"
+
+          FAILED_PACKAGES=
+          for t in $PACKAGES;do
+            make BUILD_LOG=1 CONFIG_AUTOREMOVE=y -j "$(nproc)" \
+            "package/$t/compile" || {
+                 FAILED_PACKAGES+=" $t"
+            }
           done
 
+          echo "Failed packages: $FAILED_PACKAGES"
           artifact_dir=/builder/bin/artifact
           mkdir -p $artifact_dir
-          for PKG in $PACKAGES;do
-            (cd bin/packages;find -name "$PKG*.ipk" -exec cp --parents -rv {} $artifact_dir \;)
+          
+          for t in $OFFICIAL_PACKAGES;do
+            (cd bin/packages;find -maxdepth 3 -type f -name "$t*.ipk" -exec cp --parents -rv {} $artifact_dir \;)
+          done
+
+          for t in $CUSTOM_FEEDS;do
+            (cd bin/packages;find -maxdepth 2 -type d -name "$t" -exec cp --parents -rv {} $artifact_dir \;)
           done
 
       - name: Store packages
