#

diff --git a/.github/workflows/build-latest.yml b/.github/workflows/build-latest.yml
--- a/.github/workflows/build-latest.yml
+++ b/.github/workflows/build-latest.yml
@@ -19,8 +19,8 @@ jobs:
       - name: Get latest stable tag
         id: get_latest_stable
         run: |
-          # openwrt_tag=$(curl -s https://api.github.com/repos/openwrt/openwrt/releases/latest | sed -n '/tag_name/p' | sed 's|^\s*"tag_name": "\(.*\)",|\1|')
-          [[ "${openwrt_tag}" =~ ^v[0-9] ]] || echo "get latest stable tag fail" && exit 1
+          openwrt_tag=$(curl -s https://api.github.com/repos/openwrt/openwrt/releases/latest | sed -n '/tag_name/p' | sed 's|^\s*"tag_name": "\(.*\)",|\1|')
+          [[ "${openwrt_tag}" =~ ^v[0-9] ]] || echo "error: get latest stable tag fail" && exit 1
           openwrt_branch=$(echo ${openwrt_tag} | sed 's|^v\([0-9]\+\.[0-9]\+\).*|\1|')
           echo "openwrt_tag=${openwrt_tag}" >> "$GITHUB_OUTPUT"
           echo "openwrt_branch=${openwrt_branch}" >> "$GITHUB_OUTPUT"
